### ISSUE TITLE
How to get COOKIE, KSOFT API

### ISSUE THREAD

**Issue by Only-Moon** [Milrato-Development/Milrato#1]
Include in read.me , how to get COOKIE, KSOFT API or where to get these

**Comment by Tomato6966** [comment]
Just in case u never heard from it, there is something called [https://google.com](https://google.com)

COOKIE is a YT COOKIE  https://www.youtube.com/watch?v=qymuvhBetnM
KSOFT API is KSOFT API  https://api.ksoft.si
